// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.u64().primaryKey().name("session_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  inviteCode: __t.string().name("invite_code"),
  genre: __t.string(),
  setting: __t.string(),
  styleBible: __t.string().name("style_bible"),
  totalScenes: __t.u32().name("total_scenes"),
  currentScene: __t.u32().name("current_scene"),
  generatingScene: __t.u32().name("generating_scene"),
  status: __t.string(),
  createdAt: __t.u64().name("created_at"),
  rootSessionId: __t.u64().name("root_session_id"),
  parentSessionId: __t.u64().name("parent_session_id"),
  forkSceneNum: __t.u32().name("fork_scene_num"),
  forkGenerationId: __t.u64().name("fork_generation_id"),
  branchLabel: __t.string().name("branch_label"),
  forkedAt: __t.u64().name("forked_at"),
});
