// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.u64().primaryKey().name("event_id"),
  sessionId: __t.u64().name("session_id"),
  sceneNum: __t.u32().name("scene_num"),
  kind: __t.string(),
  label: __t.string(),
  detail: __t.string(),
  done: __t.bool(),
  active: __t.bool(),
  createdAt: __t.u64().name("created_at"),
  generationId: __t.u64().name("generation_id"),
});
