// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  charId: __t.u64().primaryKey().name("char_id"),
  sessionId: __t.u64().name("session_id"),
  name: __t.string(),
  archetype: __t.string(),
  personality: __t.string(),
  currentMood: __t.string().name("current_mood"),
  secret: __t.string(),
});
