// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  coDirectorId: __t.u64().primaryKey().name("co_director_id"),
  sessionId: __t.u64().name("session_id"),
  identity: __t.identity(),
  displayName: __t.string().name("display_name"),
  joinedAt: __t.u64().name("joined_at"),
});
