// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  memoryId: __t.u64().primaryKey().name("memory_id"),
  charId: __t.u64().name("char_id"),
  sessionId: __t.u64().name("session_id"),
  sceneNum: __t.u32().name("scene_num"),
  panelNum: __t.u32().name("panel_num"),
  eventText: __t.string().name("event_text"),
});
