// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  directiveId: __t.u64().primaryKey().name("directive_id"),
  sessionId: __t.u64().name("session_id"),
  type: __t.string(),
  content: __t.string(),
  appliedAtScene: __t.u32().name("applied_at_scene"),
  appliedBy: __t.string().name("applied_by"),
});
