// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.u64().primaryKey().name("event_id"),
  sessionId: __t.u64().name("session_id"),
  targetScene: __t.u32().name("target_scene"),
  kind: __t.string(),
  type: __t.string(),
  content: __t.string(),
  actorName: __t.string().name("actor_name"),
  detail: __t.string(),
  createdAt: __t.u64().name("created_at"),
});
