// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  panelId: __t.u64().primaryKey().name("panel_id"),
  sceneId: __t.u64().name("scene_id"),
  sessionId: __t.u64().name("session_id"),
  sceneNum: __t.u32().name("scene_num"),
  panelNum: __t.u32().name("panel_num"),
  caption: __t.string(),
  speaker: __t.string(),
  dialogue: __t.string(),
  imagePrompt: __t.string().name("image_prompt"),
  imageUrl: __t.string().name("image_url"),
  layoutHint: __t.string().name("layout_hint"),
  status: __t.string(),
});
