// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.u64().primaryKey().name("session_id"),
  targetScene: __t.u32().name("target_scene"),
  type: __t.string(),
  content: __t.string(),
  submittedBy: __t.identity().name("submitted_by"),
  submittedByName: __t.string().name("submitted_by_name"),
  submittedAt: __t.u64().name("submitted_at"),
});
