// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sceneId: __t.u64().primaryKey().name("scene_id"),
  sessionId: __t.u64().name("session_id"),
  sceneNum: __t.u32().name("scene_num"),
  title: __t.string(),
  status: __t.string(),
  createdAt: __t.u64().name("created_at"),
  sceneSummary: __t.string().name("scene_summary"),
});
