// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  generationId: __t.u64().primaryKey().name("generation_id"),
  sessionId: __t.u64().name("session_id"),
  sceneNum: __t.u32().name("scene_num"),
  sourceSceneId: __t.u64().name("source_scene_id"),
  generationNum: __t.u32().name("generation_num"),
  kind: __t.string(),
  reason: __t.string(),
  title: __t.string(),
  sceneSummary: __t.string().name("scene_summary"),
  pageImageUrl: __t.string().name("page_image_url"),
  narrationAudioUrl: __t.string().name("narration_audio_url"),
  narrationSegmentsJson: __t.string().name("narration_segments_json"),
  narrationStatus: __t.string().name("narration_status"),
  panelsJson: __t.string().name("panels_json"),
  status: __t.string(),
  isCurrent: __t.bool().name("is_current"),
  createdAt: __t.u64().name("created_at"),
  supersededAt: __t.u64().name("superseded_at"),
});
