// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.u64().primaryKey().name("session_id"),
  genre: __t.string(),
  setting: __t.string(),
  styleBible: __t.string().name("style_bible"),
  totalScenes: __t.u32().name("total_scenes"),
  currentScene: __t.u32().name("current_scene"),
  status: __t.string(),
  createdAt: __t.u64().name("created_at"),
});
