// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.u64().name("session_id"),
  genre: __t.string(),
  setting: __t.string(),
  status: __t.string(),
  currentScene: __t.u32().name("current_scene"),
  totalScenes: __t.u32().name("total_scenes"),
  generatingScene: __t.u32().name("generating_scene"),
  resumeScene: __t.u32().name("resume_scene"),
  scenesDone: __t.u32().name("scenes_done"),
  isComplete: __t.bool().name("is_complete"),
  isGenerating: __t.bool().name("is_generating"),
  role: __t.string(),
  coverPageImageUrl: __t.string().name("cover_page_image_url"),
  createdAt: __t.u64().name("created_at"),
  rootSessionId: __t.u64().name("root_session_id"),
  parentSessionId: __t.u64().name("parent_session_id"),
  forkSceneNum: __t.u32().name("fork_scene_num"),
  branchLabel: __t.string().name("branch_label"),
  forkedAt: __t.u64().name("forked_at"),
  isFork: __t.bool().name("is_fork"),
  branchCount: __t.u32().name("branch_count"),
});
