// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Character = __t.object("Character", {
  charId: __t.u64(),
  sessionId: __t.u64(),
  name: __t.string(),
  archetype: __t.string(),
  personality: __t.string(),
  currentMood: __t.string(),
  secret: __t.string(),
});
export type Character = __Infer<typeof Character>;

export const CharacterInput = __t.object("CharacterInput", {
  name: __t.string(),
  archetype: __t.string(),
  personality: __t.string(),
  currentMood: __t.string(),
  secret: __t.string(),
});
export type CharacterInput = __Infer<typeof CharacterInput>;

export const Memory = __t.object("Memory", {
  memoryId: __t.u64(),
  charId: __t.u64(),
  sessionId: __t.u64(),
  sceneNum: __t.u32(),
  panelNum: __t.u32(),
  eventText: __t.string(),
});
export type Memory = __Infer<typeof Memory>;

export const NarrativeDirective = __t.object("NarrativeDirective", {
  directiveId: __t.u64(),
  sessionId: __t.u64(),
  type: __t.string(),
  content: __t.string(),
  appliedAtScene: __t.u32(),
  appliedBy: __t.string(),
});
export type NarrativeDirective = __Infer<typeof NarrativeDirective>;

export const Panel = __t.object("Panel", {
  panelId: __t.u64(),
  sceneId: __t.u64(),
  sessionId: __t.u64(),
  sceneNum: __t.u32(),
  panelNum: __t.u32(),
  caption: __t.string(),
  speaker: __t.string(),
  dialogue: __t.string(),
  imagePrompt: __t.string(),
  imageUrl: __t.string(),
  layoutHint: __t.string(),
  status: __t.string(),
});
export type Panel = __Infer<typeof Panel>;

export const Scene = __t.object("Scene", {
  sceneId: __t.u64(),
  sessionId: __t.u64(),
  sceneNum: __t.u32(),
  title: __t.string(),
  status: __t.string(),
  createdAt: __t.u64(),
  sceneSummary: __t.string(),
});
export type Scene = __Infer<typeof Scene>;

export const Session = __t.object("Session", {
  sessionId: __t.u64(),
  genre: __t.string(),
  setting: __t.string(),
  styleBible: __t.string(),
  totalScenes: __t.u32(),
  currentScene: __t.u32(),
  status: __t.string(),
  createdAt: __t.u64(),
});
export type Session = __Infer<typeof Session>;

