// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as AdvanceAndGenerateProcedure from "../advance_and_generate_procedure";
import * as GenerateSceneProcedure from "../generate_scene_procedure";
import * as RegenerateSceneNarrationProcedure from "../regenerate_scene_narration_procedure";
import * as ResumeGenerationProcedure from "../resume_generation_procedure";
import * as RetryPageNowProcedure from "../retry_page_now_procedure";
import * as StartStoryProcedure from "../start_story_procedure";

export type AdvanceAndGenerateArgs = __Infer<typeof AdvanceAndGenerateProcedure.params>;
export type AdvanceAndGenerateResult = __Infer<typeof AdvanceAndGenerateProcedure.returnType>;
export type GenerateSceneArgs = __Infer<typeof GenerateSceneProcedure.params>;
export type GenerateSceneResult = __Infer<typeof GenerateSceneProcedure.returnType>;
export type RegenerateSceneNarrationArgs = __Infer<typeof RegenerateSceneNarrationProcedure.params>;
export type RegenerateSceneNarrationResult = __Infer<typeof RegenerateSceneNarrationProcedure.returnType>;
export type ResumeGenerationArgs = __Infer<typeof ResumeGenerationProcedure.params>;
export type ResumeGenerationResult = __Infer<typeof ResumeGenerationProcedure.returnType>;
export type RetryPageNowArgs = __Infer<typeof RetryPageNowProcedure.params>;
export type RetryPageNowResult = __Infer<typeof RetryPageNowProcedure.returnType>;
export type StartStoryArgs = __Infer<typeof StartStoryProcedure.params>;
export type StartStoryResult = __Infer<typeof StartStoryProcedure.returnType>;

