// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdvanceSceneReducer from "../advance_scene_reducer";
import AppendMemoryReducer from "../append_memory_reducer";
import ApplyNudgeReducer from "../apply_nudge_reducer";
import CreateSessionReducer from "../create_session_reducer";
import ForkStoryAtSceneReducer from "../fork_story_at_scene_reducer";
import JoinSessionReducer from "../join_session_reducer";
import LeaveSessionReducer from "../leave_session_reducer";
import RegenerateInviteCodeReducer from "../regenerate_invite_code_reducer";
import RestoreGenerationReducer from "../restore_generation_reducer";
import RetryPanelNowReducer from "../retry_panel_now_reducer";
import RevokeCoDirectorReducer from "../revoke_co_director_reducer";
import SetDisplayNameReducer from "../set_display_name_reducer";
import SubmitNudgeReducer from "../submit_nudge_reducer";
import UpdateCharacterMoodReducer from "../update_character_mood_reducer";

export type AdvanceSceneParams = __Infer<typeof AdvanceSceneReducer>;
export type AppendMemoryParams = __Infer<typeof AppendMemoryReducer>;
export type ApplyNudgeParams = __Infer<typeof ApplyNudgeReducer>;
export type CreateSessionParams = __Infer<typeof CreateSessionReducer>;
export type ForkStoryAtSceneParams = __Infer<typeof ForkStoryAtSceneReducer>;
export type JoinSessionParams = __Infer<typeof JoinSessionReducer>;
export type LeaveSessionParams = __Infer<typeof LeaveSessionReducer>;
export type RegenerateInviteCodeParams = __Infer<typeof RegenerateInviteCodeReducer>;
export type RestoreGenerationParams = __Infer<typeof RestoreGenerationReducer>;
export type RetryPanelNowParams = __Infer<typeof RetryPanelNowReducer>;
export type RevokeCoDirectorParams = __Infer<typeof RevokeCoDirectorReducer>;
export type SetDisplayNameParams = __Infer<typeof SetDisplayNameReducer>;
export type SubmitNudgeParams = __Infer<typeof SubmitNudgeReducer>;
export type UpdateCharacterMoodParams = __Infer<typeof UpdateCharacterMoodReducer>;

