// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdvanceSceneReducer from "../advance_scene_reducer";
import AppendMemoryReducer from "../append_memory_reducer";
import ApplyNudgeReducer from "../apply_nudge_reducer";
import CreateSessionReducer from "../create_session_reducer";
import UpdateCharacterMoodReducer from "../update_character_mood_reducer";

export type AdvanceSceneParams = __Infer<typeof AdvanceSceneReducer>;
export type AppendMemoryParams = __Infer<typeof AppendMemoryReducer>;
export type ApplyNudgeParams = __Infer<typeof ApplyNudgeReducer>;
export type CreateSessionParams = __Infer<typeof CreateSessionReducer>;
export type UpdateCharacterMoodParams = __Infer<typeof UpdateCharacterMoodReducer>;

