#!/usr/bin/env node
/**
 * Reads spacetimedb/.env and generates compile-time constants for the module bundle.
 * SpacetimeDB modules run in a browser-like sandbox — process.env is not available at runtime.
 *
 * Keys are baked into the published module only (server-side). The Vite client never receives API keys.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const envPath = path.join(root, 'spacetimedb', '.env');
const outPath = path.join(root, 'spacetimedb', 'src', 'lib', 'env.generated.ts');

function parseEnv(text) {
  const vars = {};
  for (const line of text.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    vars[key] = value;
  }
  return vars;
}

if (!fs.existsSync(envPath)) {
  console.error('Missing spacetimedb/.env — copy from spacetimedb/.env.example');
  process.exit(1);
}

const vars = parseEnv(fs.readFileSync(envPath, 'utf8'));
const anthropic = vars.ANTHROPIC_API_KEY ?? '';
const openai = vars.OPENAI_API_KEY ?? '';

if (!anthropic || !openai) {
  console.warn('Warning: ANTHROPIC_API_KEY or OPENAI_API_KEY is empty in spacetimedb/.env');
}

const out = `// AUTO-GENERATED by scripts/inject-env.mjs — do not edit or commit
export const ANTHROPIC_API_KEY = ${JSON.stringify(anthropic)};
export const OPENAI_API_KEY = ${JSON.stringify(openai)};
`;

fs.writeFileSync(outPath, out);
console.log('Wrote spacetimedb/src/lib/env.generated.ts');
